name: webrtsp-hdmi-restreamer
base: core24
summary: Restreams video from attached with HDMI device to browser
adopt-info: restreamer
description: |
  Intended to restream video grabbed with HDMI to CSI-2 adapter (Toshiba TC358743 based) attached to Raspberry Pi Zero/3/4.
  Can act as remote Agent for WebRTSP server (https://snapcraft.io/rtsp-to-webrtsp)

  To try, install snap and open http://localhost:5080 in your browser.

  **Config file location:** /var/snap/webrtsp-hdmi-restreamer/common/v4l2-restreamer.conf

license: GPL-3.0
grade: devel
confinement: strict

platforms:
  arm64:

layout:
  /opt/${CRAFT_PROJECT_NAME}/lib:
    symlink: $SNAP/opt/${CRAFT_PROJECT_NAME}/lib

parts:
  meson-deps:
    plugin: python
    source: .
    python-packages:
      - meson
      - ninja
  gstreamer:
    plugin: meson
    source: https://github.com/GStreamer/gstreamer.git
    source-branch: 1.28
    after:
      - meson-deps
    build-packages:
      - flex
      - bison
      - nasm
      - libsrtp2-dev
    meson-parameters:
      - --prefix=/opt/${SNAPCRAFT_PROJECT_NAME}
      - --buildtype=release
      - -Dbase=enabled
      - -Dgood=enabled
      - -Dbad=enabled
      - -Dugly=enabled
      - -Dlibav=disabled
      - -Ddevtools=disabled
      - -Dges=disabled
      - -Drtsp_server=disabled
      - -Dgst-examples=disabled
      - -Dpython=disabled
      - -Dgpl=disabled
      - -Dbenchmarks=disabled
      - -Dtools=disabled
      - -Dqt5=disabled
      - -Dqt6=disabled
      - -Dtests=disabled
      - -Dexamples=disabled
      - -Dintrospection=disabled
      - -Dnls=disabled
    stage-packages:
      - libunwind8
      - libdw1
      - libupnp17t64
      - libgupnp-igd-1.6-0
      - libsrtp2-1
  restreamer:
    plugin: cmake
    source-type: git
    source: https://github.com/WebRTSP/ReStreamer.git
    build-environment:
      - PKG_CONFIG_PATH: ${CRAFT_STAGE}/opt/${CRAFT_PROJECT_NAME}/lib/pkgconfig:${CRAFT_STAGE}/opt/${CRAFT_PROJECT_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}/pkgconfig:${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: ${CRAFT_STAGE}/opt/${CRAFT_PROJECT_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/${CRAFT_PROJECT_NAME}
      - -DV4L2_RESTREAMER=ON
    override-pull: |
        craftctl default
        craftctl set version="$(git describe --always)"
    after:
      - gstreamer
    build-snaps:
      - node/24/stable
    build-packages:
      - g++
      - ninja-build
      - libspdlog-dev
      - libconfig-dev
      - libmicrohttpd-dev
      - libwebsockets-dev
    stage-packages:
      - libconfig9
      - libx264-164
      - libspdlog1.12
      - libmicrohttpd12
      - libwebsockets19t64
      - libwebsockets-evlib-glib
      - v4l-utils
apps:
  V4L2ReStreamer:
    command: opt/${CRAFT_PROJECT_NAME}/bin/V4L2ReStreamer
    daemon: simple
    plugs:
      - network-bind
      - network
      - camera
      - media-control
      - opengl
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/${SNAP_NAME}/lib:$SNAP/opt/${SNAP_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}:${LD_LIBRARY_PATH}
      GST_DEBUG: 2
      GST_DEBUG_NO_COLOR: 1
      GST_PLUGIN_PATH: $SNAP/opt/${SNAP_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/opt/${SNAP_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/opt/${SNAP_NAME}/libexec/gstreamer-1.0/gst-plugin-scanner
